/**
 * Sample data for the "Load Sample Company" feature.
 * All data is realistic landscaping contractor data for the Austin TX area.
 * org_id is NOT included — it's added at insert time.
 */

import type { Project, Material, CrewMember, Equipment, TaskPhase, TaskStatus } from '@/types';

// ── Date helpers ─────────────────────────────────────────────────────────────

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
}

// ── Projects ─────────────────────────────────────────────────────────────────

export function getSampleProjects(): Omit<Project, 'id' | 'createdAt'>[] {
  return [
    {
      name: 'Riverside Patio & Firepit',
      client: 'Mike & Laura Chen',
      address: '2418 Riverside Dr, Austin TX 78741',
      lat: 30.2432,
      lng: -97.7280,
      totalArea: 2800,
      startDate: daysFromNow(-14),
      targetDate: daysFromNow(28),
      budget: 38000,
      notes: '[SAMPLE] Full backyard renovation with stone patio, gas firepit, and pathway lighting.',
      checklist: {
        permit: true,
        utility: true,
        deposit: true,
        design: true,
        access: true,
        materials: true,
        crew: false,
        equipment: false,
      },
      zones: [
        {
          id: '', name: 'Main Patio', area: 1200, perimeter: 140, sequence: 1,
          crew: '', dependencies: [], notes: 'Belgard pavers on compacted base',
          materials: [], equipment: [], createdAt: '',
        },
        {
          id: '', name: 'Firepit Area', area: 400, perimeter: 72, sequence: 2,
          crew: '', dependencies: [], notes: 'Circular firepit with limestone surround',
          materials: [], equipment: [], createdAt: '',
        },
        {
          id: '', name: 'Pathway', area: 1200, perimeter: 320, sequence: 3,
          crew: '', dependencies: [], notes: 'Stepping stone path with low-voltage lighting',
          materials: [], equipment: [], createdAt: '',
        },
      ],
    },
    {
      name: 'Cedar Park Front Yard',
      client: 'Oakridge HOA',
      address: '1205 Brushy Creek Rd, Cedar Park TX 78613',
      lat: 30.5052,
      lng: -97.8203,
      totalArea: 3400,
      startDate: daysFromNow(7),
      targetDate: daysFromNow(42),
      budget: 22000,
      notes: '[SAMPLE] Front yard renovation for HOA compliance — new sod, edging, and garden beds.',
      checklist: {
        permit: false,
        utility: false,
        deposit: true,
        design: true,
        access: false,
        materials: false,
        crew: false,
        equipment: false,
      },
      zones: [
        {
          id: '', name: 'Driveway Border', area: 800, perimeter: 120, sequence: 1,
          crew: '', dependencies: [], notes: 'Steel edging with mulch beds',
          materials: [], equipment: [], createdAt: '',
        },
        {
          id: '', name: 'Garden Beds', area: 2600, perimeter: 200, sequence: 2,
          crew: '', dependencies: [], notes: 'Native plantings with drip irrigation',
          materials: [], equipment: [], createdAt: '',
        },
      ],
    },
    {
      name: 'Thompson Pool Deck',
      client: 'James Thompson',
      address: '4500 Lago Vista Blvd, Lago Vista TX 78645',
      lat: 30.4628,
      lng: -97.9883,
      totalArea: 4200,
      startDate: daysFromNow(21),
      targetDate: daysFromNow(70),
      budget: 55000,
      notes: '[SAMPLE] Premium pool deck with travertine pavers and landscape ring — high-end residential.',
      checklist: {
        permit: false,
        utility: false,
        deposit: false,
        design: true,
        access: false,
        materials: false,
        crew: false,
        equipment: false,
      },
      zones: [
        {
          id: '', name: 'Pool Deck', area: 2800, perimeter: 210, sequence: 1,
          crew: '', dependencies: [], notes: 'Travertine pavers with non-slip finish',
          materials: [], equipment: [], createdAt: '',
        },
        {
          id: '', name: 'Landscape Ring', area: 1400, perimeter: 180, sequence: 2,
          crew: '', dependencies: [], notes: 'Ornamental grasses and specimen trees',
          materials: [], equipment: [], createdAt: '',
        },
      ],
    },
  ];
}

// ── Sample Tasks ────────────────────────────────────────────────────────────

export interface SampleTask {
  name: string;
  description: string;
  phase: TaskPhase;
  status: TaskStatus;
  sequenceNumber: number;
  aiGenerated: boolean;
}

/** Returns sample tasks keyed by project name */
export function getSampleTasks(): Record<string, SampleTask[]> {
  return {
    'Riverside Patio & Firepit': [
      { name: 'Clear existing vegetation', description: 'Remove grass, weeds, and small shrubs from the patio footprint', phase: 'rough_grade', status: 'pending', sequenceNumber: 1, aiGenerated: false },
      { name: 'Grade and level patio area', description: 'Establish proper slope for drainage (1% away from house)', phase: 'rough_grade', status: 'pending', sequenceNumber: 2, aiGenerated: false },
      { name: 'Install gravel base', description: 'Lay 4" compacted #57 limestone base across all zones', phase: 'rough_grade', status: 'pending', sequenceNumber: 3, aiGenerated: false },
      { name: 'Lay paver base and edge restraints', description: 'Set 1" sand bedding layer and install poly edge restraints', phase: 'hardscape', status: 'pending', sequenceNumber: 4, aiGenerated: false },
      { name: 'Install flagstone pavers', description: 'Lay Belgard Cambridge pavers in running bond pattern', phase: 'hardscape', status: 'pending', sequenceNumber: 5, aiGenerated: false },
      { name: 'Build firepit structure', description: 'Construct circular gas firepit with limestone surround', phase: 'hardscape', status: 'pending', sequenceNumber: 6, aiGenerated: false },
      { name: 'Apply polymeric sand', description: 'Fill paver joints and activate with water', phase: 'cleanup_punchlist', status: 'pending', sequenceNumber: 7, aiGenerated: false },
      { name: 'Final grading and cleanup', description: 'Dress edges, clean pavers, haul debris', phase: 'cleanup_punchlist', status: 'pending', sequenceNumber: 8, aiGenerated: false },
    ],
    'Cedar Park Front Yard': [
      { name: 'Remove existing lawn and shrubs', description: 'Strip old bermuda sod and remove overgrown foundation plantings', phase: 'demo_prep', status: 'pending', sequenceNumber: 1, aiGenerated: false },
      { name: 'Clear planting beds', description: 'Remove old mulch and amend soil in garden bed areas', phase: 'demo_prep', status: 'pending', sequenceNumber: 2, aiGenerated: false },
      { name: 'Install drip irrigation lines', description: 'Run drip tubing through all garden beds with Hunter MP rotators', phase: 'irrigation', status: 'pending', sequenceNumber: 3, aiGenerated: false },
      { name: 'Connect to main water supply', description: 'Tie drip system into existing irrigation mainline', phase: 'irrigation', status: 'pending', sequenceNumber: 4, aiGenerated: false },
      { name: 'Plant trees and large shrubs', description: 'Install Live Oaks and specimen shrubs per design plan', phase: 'softscape', status: 'pending', sequenceNumber: 5, aiGenerated: false },
      { name: 'Install sod', description: 'Lay premium bermuda sod in all lawn areas', phase: 'softscape', status: 'pending', sequenceNumber: 6, aiGenerated: false },
      { name: 'Mulch all beds', description: 'Apply 3" hardwood mulch to all planting beds', phase: 'softscape', status: 'pending', sequenceNumber: 7, aiGenerated: false },
      { name: 'Install landscape lighting', description: 'Place low-voltage path lights and uplights on trees', phase: 'lighting', status: 'pending', sequenceNumber: 8, aiGenerated: false },
      { name: 'Final walkthrough', description: 'HOA compliance check and client sign-off', phase: 'cleanup_punchlist', status: 'pending', sequenceNumber: 9, aiGenerated: false },
    ],
    'Thompson Pool Deck': [
      { name: 'Excavate deck area', description: 'Remove 6" of soil across pool deck footprint', phase: 'rough_grade', status: 'pending', sequenceNumber: 1, aiGenerated: false },
      { name: 'Compact subgrade', description: 'Plate-compact native soil to 95% density', phase: 'rough_grade', status: 'pending', sequenceNumber: 2, aiGenerated: false },
      { name: 'Install drainage', description: 'Set channel drains at deck perimeter for pool splash runoff', phase: 'rough_grade', status: 'pending', sequenceNumber: 3, aiGenerated: false },
      { name: 'Pour concrete pad', description: 'Place 4" reinforced concrete slab as paver substrate', phase: 'hardscape', status: 'pending', sequenceNumber: 4, aiGenerated: false },
      { name: 'Install stone veneer on pool edge', description: 'Apply travertine coping stones to pool beam', phase: 'hardscape', status: 'pending', sequenceNumber: 5, aiGenerated: false },
      { name: 'Lay deck pavers', description: 'Set travertine pavers with non-slip finish on mortar bed', phase: 'hardscape', status: 'pending', sequenceNumber: 6, aiGenerated: false },
      { name: 'Seal all surfaces', description: 'Apply penetrating sealer to deck and coping', phase: 'cleanup_punchlist', status: 'pending', sequenceNumber: 7, aiGenerated: false },
      { name: 'Install pool fence sections', description: 'Mount aluminum fence panels per code requirements', phase: 'cleanup_punchlist', status: 'pending', sequenceNumber: 8, aiGenerated: false },
      { name: 'Final inspection', description: 'City inspection for pool barrier compliance', phase: 'cleanup_punchlist', status: 'pending', sequenceNumber: 9, aiGenerated: false },
    ],
  };
}

// ── Crew ─────────────────────────────────────────────────────────────────────

export function getSampleCrew(): Omit<CrewMember, 'id'>[] {
  return [
    {
      name: 'Marco Gutierrez',
      role: 'foreman',
      skills: ['hardscape', 'grading'],
      availability: { mon: true, tue: true, wed: true, thu: true, fri: true, sat: false, sun: false },
      maxProjects: 2,
      notes: '[SAMPLE] 12 years experience, bilingual.',
      bookedDates: [],
      certs: [{ certId: 'cert-1', label: 'ICPI Certified', expiry: daysFromNow(180) }],
    },
    {
      name: 'James Wilson',
      role: 'lead',
      skills: ['hardscape', 'concrete'],
      availability: { mon: true, tue: true, wed: true, thu: true, fri: true, sat: false, sun: false },
      maxProjects: 2,
      notes: '[SAMPLE] Concrete finishing specialist.',
      bookedDates: [],
      certs: [],
    },
    {
      name: 'Sofia Reyes',
      role: 'specialist',
      skills: ['planting', 'irrigation'],
      availability: { mon: true, tue: true, wed: true, thu: true, fri: true, sat: true, sun: false },
      maxProjects: 3,
      notes: '[SAMPLE] Horticulture degree, irrigation design.',
      bookedDates: [],
      certs: [{ certId: 'cert-2', label: 'Irrigation Assoc. Certified', expiry: daysFromNow(365) }],
    },
    {
      name: 'Tyler Brooks',
      role: 'installer',
      skills: ['grading', 'demolition'],
      availability: { mon: true, tue: true, wed: true, thu: true, fri: true, sat: false, sun: false },
      maxProjects: 2,
      notes: '[SAMPLE] Heavy equipment operator.',
      bookedDates: [],
      certs: [],
    },
    {
      name: 'David Chen',
      role: 'apprentice',
      skills: ['general labor'],
      availability: { mon: true, tue: true, wed: true, thu: true, fri: true, sat: false, sun: false },
      maxProjects: 1,
      notes: '[SAMPLE] First year apprentice, eager learner.',
      bookedDates: [],
      certs: [],
    },
    {
      name: 'Ana Martinez',
      role: 'specialist',
      skills: ['design', 'estimation'],
      availability: { mon: true, tue: true, wed: true, thu: true, fri: false, sat: false, sun: false },
      maxProjects: 3,
      notes: '[SAMPLE] Landscape designer / project manager.',
      bookedDates: [],
      certs: [],
    },
  ];
}

// ── Equipment ────────────────────────────────────────────────────────────────

export function getSampleEquipment(): Omit<Equipment, 'id'>[] {
  return [
    {
      name: 'CAT 303.5 Mini Excavator',
      type: 'Excavator',
      makeModel: 'Caterpillar 303.5',
      year: 2022,
      serial: 'CAT303-2022-4871',
      plate: '',
      status: 'available',
      assignedProject: '',
      location: 'Main yard',
      operator: '',
      hours: 1240,
      serviceDueHours: 1500,
      lastService: daysFromNow(-30),
      nextService: daysFromNow(60),
      maintNotes: '[SAMPLE]',
      value: 62000,
      dailyRate: 350,
      insurance: 'State Farm Commercial',
      insuranceExpiry: daysFromNow(180),
      regExpiry: daysFromNow(270),
      inspectionDue: daysFromNow(90),
      notes: '[SAMPLE] Primary excavation unit for residential jobs.',
      capabilities: ['excavation', 'grading', 'trenching'],
      maintenanceLog: [],
    },
    {
      name: 'Bobcat S570 Skid Steer',
      type: 'Skid Steer',
      makeModel: 'Bobcat S570',
      year: 2023,
      serial: 'BOB570-2023-1192',
      plate: '',
      status: 'in-use',
      assignedProject: '',
      location: 'Riverside job site',
      operator: '',
      hours: 680,
      serviceDueHours: 1000,
      lastService: daysFromNow(-15),
      nextService: daysFromNow(75),
      maintNotes: '[SAMPLE]',
      value: 48000,
      dailyRate: 275,
      insurance: 'State Farm Commercial',
      insuranceExpiry: daysFromNow(180),
      regExpiry: daysFromNow(270),
      inspectionDue: daysFromNow(120),
      notes: '[SAMPLE] Versatile loader for material handling.',
      capabilities: ['loading', 'grading', 'material handling'],
      maintenanceLog: [],
    },
    {
      name: 'Ford F-350 Dump Truck',
      type: 'Truck',
      makeModel: 'Ford F-350 XL',
      year: 2021,
      serial: '1FTRF3B6XMEC18472',
      plate: 'TX-LND-4821',
      status: 'available',
      assignedProject: '',
      location: 'Main yard',
      operator: '',
      hours: 28500,
      serviceDueHours: 30000,
      lastService: daysFromNow(-20),
      nextService: daysFromNow(40),
      maintNotes: '[SAMPLE]',
      value: 38000,
      dailyRate: 150,
      insurance: 'Progressive Commercial',
      insuranceExpiry: daysFromNow(240),
      regExpiry: daysFromNow(180),
      inspectionDue: daysFromNow(60),
      notes: '[SAMPLE] Daily hauling — material delivery and debris removal.',
      capabilities: ['hauling', 'material delivery'],
      maintenanceLog: [],
    },
    {
      name: 'Wacker Neuson WP1550 Compactor',
      type: 'Compactor',
      makeModel: 'Wacker Neuson WP1550',
      year: 2024,
      serial: 'WN1550-2024-0337',
      plate: '',
      status: 'available',
      assignedProject: '',
      location: 'Main yard',
      operator: '',
      hours: 220,
      serviceDueHours: 500,
      lastService: daysFromNow(-45),
      nextService: daysFromNow(120),
      maintNotes: '[SAMPLE]',
      value: 5800,
      dailyRate: 75,
      insurance: '',
      insuranceExpiry: '',
      regExpiry: '',
      inspectionDue: '',
      notes: '[SAMPLE] Plate compactor for paver base.',
      capabilities: ['compaction'],
      maintenanceLog: [],
    },
    {
      name: 'Vermeer BC700XL Chipper',
      type: 'Chipper',
      makeModel: 'Vermeer BC700XL',
      year: 2020,
      serial: 'VER700-2020-8814',
      plate: '',
      status: 'maintenance',
      assignedProject: '',
      location: 'Main yard — service bay',
      operator: '',
      hours: 1950,
      serviceDueHours: 2000,
      lastService: daysFromNow(-5),
      nextService: daysFromNow(5),
      maintNotes: '[SAMPLE] Blade sharpening in progress.',
      value: 24000,
      dailyRate: 200,
      insurance: 'State Farm Commercial',
      insuranceExpiry: daysFromNow(180),
      regExpiry: '',
      inspectionDue: daysFromNow(30),
      notes: '[SAMPLE] Wood chipper — scheduled for blade maintenance.',
      capabilities: ['chipping', 'brush removal'],
      maintenanceLog: [],
    },
  ];
}

// ── Materials ────────────────────────────────────────────────────────────────

export function getSampleMaterials(): Omit<Material, 'id'>[] {
  return [
    {
      name: 'Belgard Cambridge Pavers',
      category: 'paver',
      unit: 'sqft',
      cost: 4.50,
      reserveOverride: null,
      coverage: 1,
      depthIn: null,
      notes: '[SAMPLE]',
      supplier_name: 'Austin Stone Supply',
      supplier_sku: 'BEL-CAM-GRY',
      supplier_phone: '(512) 555-0140',
      supplier_contact: 'Tony R.',
      lead_time_days: 5,
      price_update_date: daysFromNow(-10),
      supplier_notes: '',
      qtyOnHand: 2400,
      minStockLevel: 500,
      storageLocation: 'Yard A - Pallet 3',
      lastRestocked: daysFromNow(-7),
    },
    {
      name: 'Austin Cream Limestone',
      category: 'stone',
      unit: 'sqft',
      cost: 8.75,
      reserveOverride: null,
      coverage: 1,
      depthIn: null,
      notes: '[SAMPLE]',
      supplier_name: 'Hill Country Stone',
      supplier_sku: 'HCS-ACL-18',
      supplier_phone: '(512) 555-0188',
      supplier_contact: 'Maria G.',
      lead_time_days: 10,
      price_update_date: daysFromNow(-14),
      supplier_notes: 'Call 48hr ahead for large orders',
      qtyOnHand: 800,
      minStockLevel: 200,
      storageLocation: 'Yard A - Pallet 7',
      lastRestocked: daysFromNow(-14),
    },
    {
      name: 'Bermuda Sod (premium)',
      category: 'sod',
      unit: 'sqft',
      cost: 0.85,
      reserveOverride: null,
      coverage: 1,
      depthIn: null,
      notes: '[SAMPLE]',
      supplier_name: 'Emerald Sod Farms',
      supplier_sku: 'ESF-BERM-P',
      supplier_phone: '(512) 555-0222',
      supplier_contact: 'Jake L.',
      lead_time_days: 2,
      price_update_date: daysFromNow(-3),
      supplier_notes: 'Same-day delivery available',
      qtyOnHand: 0,
      minStockLevel: 0,
      storageLocation: '',
      lastRestocked: '',
    },
    {
      name: 'Hardwood Mulch',
      category: 'mulch',
      unit: 'cuyd',
      cost: 45,
      reserveOverride: null,
      coverage: 324,
      depthIn: 3,
      notes: '[SAMPLE]',
      supplier_name: 'Austin Landscape Supply',
      supplier_sku: 'ALS-HWM-3',
      supplier_phone: '(512) 555-0105',
      supplier_contact: 'Dave P.',
      lead_time_days: 1,
      price_update_date: daysFromNow(-5),
      supplier_notes: '',
      qtyOnHand: 12,
      minStockLevel: 5,
      storageLocation: 'Yard B - Bin 2',
      lastRestocked: daysFromNow(-5),
    },
    {
      name: '#57 Limestone Gravel',
      category: 'gravel',
      unit: 'ton',
      cost: 38,
      reserveOverride: null,
      coverage: 100,
      depthIn: 4,
      notes: '[SAMPLE]',
      supplier_name: 'Capitol Aggregates',
      supplier_sku: 'CA-57LG-T',
      supplier_phone: '(512) 555-0310',
      supplier_contact: 'Sam W.',
      lead_time_days: 3,
      price_update_date: daysFromNow(-20),
      supplier_notes: '10-ton minimum for delivery',
      qtyOnHand: 8,
      minStockLevel: 3,
      storageLocation: 'Yard B - Pile 1',
      lastRestocked: daysFromNow(-20),
    },
    {
      name: 'Steel Landscape Edging',
      category: 'edging',
      unit: 'lnft',
      cost: 3.25,
      reserveOverride: null,
      coverage: 1,
      depthIn: null,
      notes: '[SAMPLE]',
      supplier_name: 'Austin Stone Supply',
      supplier_sku: 'ASS-SLE-14',
      supplier_phone: '(512) 555-0140',
      supplier_contact: 'Tony R.',
      lead_time_days: 3,
      price_update_date: daysFromNow(-10),
      supplier_notes: '',
      qtyOnHand: 200,
      minStockLevel: 50,
      storageLocation: 'Yard A - Rack 1',
      lastRestocked: daysFromNow(-10),
    },
    {
      name: 'Live Oak (30gal)',
      category: 'tree',
      unit: 'each',
      cost: 285,
      reserveOverride: null,
      coverage: null,
      depthIn: null,
      notes: '[SAMPLE]',
      supplier_name: 'Barton Springs Nursery',
      supplier_sku: 'BSN-LO-30',
      supplier_phone: '(512) 555-0455',
      supplier_contact: 'Lisa M.',
      lead_time_days: 7,
      price_update_date: daysFromNow(-21),
      supplier_notes: 'Seasonal availability — order early',
      qtyOnHand: 0,
      minStockLevel: 0,
      storageLocation: '',
      lastRestocked: '',
    },
    {
      name: 'Hunter MP Rotator',
      category: 'irrigation',
      unit: 'each',
      cost: 12.50,
      reserveOverride: null,
      coverage: null,
      depthIn: null,
      notes: '[SAMPLE]',
      supplier_name: 'SiteOne Landscape Supply',
      supplier_sku: 'S1-HMPR-90',
      supplier_phone: '(512) 555-0520',
      supplier_contact: 'Carlos D.',
      lead_time_days: 2,
      price_update_date: daysFromNow(-8),
      supplier_notes: '',
      qtyOnHand: 48,
      minStockLevel: 12,
      storageLocation: 'Warehouse - Shelf C4',
      lastRestocked: daysFromNow(-8),
    },
  ];
}
